export type Country = {
  flag: string
  name: string
  aliases?: string[]
}

function norm(s: string): string {
  return s.trim().toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/['\-]/g, ' ').replace(/\s+/g, ' ')
}

export function matchesCountry(guess: string, country: Country): boolean {
  const g = norm(guess)
  if (g === norm(country.name)) return true
  return country.aliases?.some(a => g === norm(a)) ?? false
}

export const EASY_COUNTRIES: Country[] = [
  { flag: '🇫🇷', name: 'France' },
  { flag: '🇩🇪', name: 'Allemagne', aliases: ['Germany'] },
  { flag: '🇮🇹', name: 'Italie' },
  { flag: '🇪🇸', name: 'Espagne' },
  { flag: '🇵🇹', name: 'Portugal' },
  { flag: '🇬🇧', name: 'Royaume-Uni', aliases: ['Angleterre', 'Angletere', 'Grande-Bretagne', 'Grande Bretagne'] },
  { flag: '🇳🇱', name: 'Pays-Bas', aliases: ['Hollande', 'Netherlands'] },
  { flag: '🇧🇪', name: 'Belgique' },
  { flag: '🇨🇭', name: 'Suisse' },
  { flag: '🇦🇹', name: 'Autriche' },
  { flag: '🇸🇪', name: 'Suède' },
  { flag: '🇳🇴', name: 'Norvège' },
  { flag: '🇩🇰', name: 'Danemark' },
  { flag: '🇫🇮', name: 'Finlande' },
  { flag: '🇵🇱', name: 'Pologne' },
  { flag: '🇬🇷', name: 'Grèce' },
  { flag: '🇷🇴', name: 'Roumanie' },
  { flag: '🇭🇺', name: 'Hongrie' },
  { flag: '🇨🇿', name: 'Tchéquie', aliases: ['République tchèque', 'Republique tcheque'] },
  { flag: '🇷🇺', name: 'Russie' },
  { flag: '🇺🇦', name: 'Ukraine' },
  { flag: '🇺🇸', name: 'États-Unis', aliases: ['Etats-Unis', 'Etats Unis', 'USA', 'Amérique', 'Amerique'] },
  { flag: '🇨🇦', name: 'Canada' },
  { flag: '🇲🇽', name: 'Mexique' },
  { flag: '🇧🇷', name: 'Brésil' },
  { flag: '🇦🇷', name: 'Argentine' },
  { flag: '🇨🇱', name: 'Chili' },
  { flag: '🇨🇴', name: 'Colombie' },
  { flag: '🇵🇪', name: 'Pérou' },
  { flag: '🇻🇪', name: 'Venezuela' },
  { flag: '🇨🇺', name: 'Cuba' },
  { flag: '🇯🇲', name: 'Jamaïque' },
  { flag: '🇨🇳', name: 'Chine' },
  { flag: '🇯🇵', name: 'Japon' },
  { flag: '🇰🇷', name: 'Corée du Sud', aliases: ['Coree du Sud', 'Corée'] },
  { flag: '🇮🇳', name: 'Inde' },
  { flag: '🇦🇺', name: 'Australie' },
  { flag: '🇳🇿', name: 'Nouvelle-Zélande', aliases: ['Nouvelle Zelande'] },
  { flag: '🇹🇷', name: 'Turquie' },
  { flag: '🇸🇦', name: 'Arabie Saoudite' },
  { flag: '🇮🇱', name: 'Israël', aliases: ['Israel'] },
  { flag: '🇮🇷', name: 'Iran' },
  { flag: '🇪🇬', name: 'Égypte', aliases: ['Egypte'] },
  { flag: '🇲🇦', name: 'Maroc' },
  { flag: '🇩🇿', name: 'Algérie', aliases: ['Algerie'] },
  { flag: '🇳🇬', name: 'Nigéria', aliases: ['Nigeria'] },
  { flag: '🇿🇦', name: 'Afrique du Sud' },
  { flag: '🇰🇪', name: 'Kenya' },
  { flag: '🇹🇭', name: 'Thaïlande', aliases: ['Thailande'] },
  { flag: '🇻🇳', name: 'Vietnam' },
  { flag: '🇵🇭', name: 'Philippines' },
  { flag: '🇮🇩', name: 'Indonésie', aliases: ['Indonesie'] },
]

export const HARD_COUNTRIES: Country[] = [
  { flag: '🇮🇸', name: 'Islande' },
  { flag: '🇮🇪', name: 'Irlande' },
  { flag: '🇱🇺', name: 'Luxembourg' },
  { flag: '🇲🇹', name: 'Malte' },
  { flag: '🇨🇾', name: 'Chypre' },
  { flag: '🇸🇰', name: 'Slovaquie' },
  { flag: '🇸🇮', name: 'Slovénie', aliases: ['Slovenie'] },
  { flag: '🇭🇷', name: 'Croatie' },
  { flag: '🇧🇦', name: 'Bosnie-Herzégovine', aliases: ['Bosnie'] },
  { flag: '🇷🇸', name: 'Serbie' },
  { flag: '🇲🇪', name: 'Monténégro', aliases: ['Montenegro'] },
  { flag: '🇦🇱', name: 'Albanie' },
  { flag: '🇲🇰', name: 'Macédoine du Nord', aliases: ['Macedoine'] },
  { flag: '🇧🇬', name: 'Bulgarie' },
  { flag: '🇱🇹', name: 'Lituanie' },
  { flag: '🇱🇻', name: 'Lettonie' },
  { flag: '🇪🇪', name: 'Estonie' },
  { flag: '🇧🇾', name: 'Biélorussie', aliases: ['Bielorussie', 'Belarus'] },
  { flag: '🇲🇩', name: 'Moldavie' },
  { flag: '🇬🇪', name: 'Géorgie', aliases: ['Georgie'] },
  { flag: '🇦🇲', name: 'Arménie', aliases: ['Armenie'] },
  { flag: '🇦🇿', name: 'Azerbaïdjan', aliases: ['Azerbaidjan'] },
  { flag: '🇰🇿', name: 'Kazakhstan' },
  { flag: '🇺🇿', name: 'Ouzbékistan', aliases: ['Ouzbekistan'] },
  { flag: '🇹🇲', name: 'Turkménistan', aliases: ['Turkmenistan'] },
  { flag: '🇹🇯', name: 'Tadjikistan' },
  { flag: '🇰🇬', name: 'Kirghizistan' },
  { flag: '🇦🇫', name: 'Afghanistan' },
  { flag: '🇵🇰', name: 'Pakistan' },
  { flag: '🇧🇩', name: 'Bangladesh' },
  { flag: '🇱🇰', name: 'Sri Lanka' },
  { flag: '🇳🇵', name: 'Népal', aliases: ['Nepal'] },
  { flag: '🇲🇲', name: 'Myanmar', aliases: ['Birmanie'] },
  { flag: '🇰🇭', name: 'Cambodge' },
  { flag: '🇱🇦', name: 'Laos' },
  { flag: '🇲🇾', name: 'Malaisie' },
  { flag: '🇸🇬', name: 'Singapour' },
  { flag: '🇧🇳', name: 'Brunei' },
  { flag: '🇹🇱', name: 'Timor oriental' },
  { flag: '🇲🇳', name: 'Mongolie' },
  { flag: '🇰🇵', name: 'Corée du Nord' },
  { flag: '🇹🇼', name: 'Taïwan', aliases: ['Taiwan'] },
  { flag: '🇮🇶', name: 'Irak' },
  { flag: '🇸🇾', name: 'Syrie' },
  { flag: '🇱🇧', name: 'Liban' },
  { flag: '🇯🇴', name: 'Jordanie' },
  { flag: '🇰🇼', name: 'Koweït', aliases: ['Koweit'] },
  { flag: '🇶🇦', name: 'Qatar' },
  { flag: '🇦🇪', name: 'Émirats arabes unis', aliases: ['Emirats arabes unis', 'EAU', 'Emirats'] },
  { flag: '🇴🇲', name: 'Oman' },
  { flag: '🇾🇪', name: 'Yémen', aliases: ['Yemen'] },
  { flag: '🇧🇭', name: 'Bahreïn', aliases: ['Bahrein'] },
  { flag: '🇺🇾', name: 'Uruguay' },
  { flag: '🇵🇾', name: 'Paraguay' },
  { flag: '🇧🇴', name: 'Bolivie' },
  { flag: '🇪🇨', name: 'Équateur', aliases: ['Equateur'] },
  { flag: '🇸🇷', name: 'Suriname' },
  { flag: '🇬🇾', name: 'Guyana' },
  { flag: '🇵🇦', name: 'Panama' },
  { flag: '🇨🇷', name: 'Costa Rica' },
  { flag: '🇳🇮', name: 'Nicaragua' },
  { flag: '🇭🇳', name: 'Honduras' },
  { flag: '🇬🇹', name: 'Guatemala' },
  { flag: '🇧🇿', name: 'Belize' },
  { flag: '🇸🇻', name: 'Salvador', aliases: ['El Salvador'] },
  { flag: '🇩🇴', name: 'République dominicaine', aliases: ['Republique dominicaine'] },
  { flag: '🇭🇹', name: 'Haïti', aliases: ['Haiti'] },
  { flag: '🇵🇷', name: 'Porto Rico' },
  { flag: '🇹🇳', name: 'Tunisie' },
  { flag: '🇱🇾', name: 'Libye' },
  { flag: '🇸🇩', name: 'Soudan' },
  { flag: '🇸🇸', name: 'Soudan du Sud' },
  { flag: '🇪🇹', name: 'Éthiopie', aliases: ['Ethiopie'] },
  { flag: '🇪🇷', name: 'Érythrée', aliases: ['Erythree'] },
  { flag: '🇩🇯', name: 'Djibouti' },
  { flag: '🇸🇴', name: 'Somalie' },
  { flag: '🇺🇬', name: 'Ouganda' },
  { flag: '🇹🇿', name: 'Tanzanie' },
  { flag: '🇷🇼', name: 'Rwanda' },
  { flag: '🇧🇮', name: 'Burundi' },
  { flag: '🇲🇿', name: 'Mozambique' },
  { flag: '🇿🇼', name: 'Zimbabwe' },
  { flag: '🇿🇲', name: 'Zambie' },
  { flag: '🇲🇼', name: 'Malawi' },
  { flag: '🇧🇼', name: 'Botswana' },
  { flag: '🇳🇦', name: 'Namibie' },
  { flag: '🇦🇴', name: 'Angola' },
  { flag: '🇨🇩', name: 'Congo (RDC)', aliases: ['RDC', 'Congo democratique', 'Congo kinshasa'] },
  { flag: '🇨🇬', name: 'Congo (République)', aliases: ['Congo brazzaville'] },
  { flag: '🇨🇲', name: 'Cameroun' },
  { flag: '🇬🇭', name: 'Ghana' },
  { flag: '🇨🇮', name: 'Côte d\'Ivoire', aliases: ['Cote d\'Ivoire', 'Cote dIvoire'] },
  { flag: '🇸🇳', name: 'Sénégal', aliases: ['Senegal'] },
  { flag: '🇲🇱', name: 'Mali' },
  { flag: '🇧🇫', name: 'Burkina Faso' },
  { flag: '🇳🇪', name: 'Niger' },
  { flag: '🇨🇭', name: 'Tchad', aliases: ['Chad'] },
  { flag: '🇲🇷', name: 'Mauritanie' },
  { flag: '🇬🇳', name: 'Guinée', aliases: ['Guinee'] },
  { flag: '🇸🇱', name: 'Sierra Leone' },
  { flag: '🇱🇷', name: 'Libéria', aliases: ['Liberia'] },
  { flag: '🇬🇲', name: 'Gambie' },
  { flag: '🇬🇼', name: 'Guinée-Bissau', aliases: ['Guinee-Bissau'] },
  { flag: '🇨🇻', name: 'Cap-Vert' },
  { flag: '🇸🇹', name: 'Sao Tomé-et-Principe' },
  { flag: '🇬🇶', name: 'Guinée équatoriale', aliases: ['Guinee equatoriale'] },
  { flag: '🇬🇦', name: 'Gabon' },
  { flag: '🇨🇫', name: 'République centrafricaine', aliases: ['Centrafrique'] },
  { flag: '🇹🇩', name: 'Tchad' },
  { flag: '🇲🇬', name: 'Madagascar' },
  { flag: '🇸🇨', name: 'Seychelles' },
  { flag: '🇲🇺', name: 'Maurice' },
  { flag: '🇰🇲', name: 'Comores' },
  { flag: '🇫🇯', name: 'Fidji' },
  { flag: '🇵🇬', name: 'Papouasie-Nouvelle-Guinée' },
  { flag: '🇸🇧', name: 'Îles Salomon', aliases: ['Iles Salomon'] },
  { flag: '🇻🇺', name: 'Vanuatu' },
  { flag: '🇼🇸', name: 'Samoa' },
  { flag: '🇹🇴', name: 'Tonga' },
  { flag: '🇰🇮', name: 'Kiribati' },
  { flag: '🇫🇲', name: 'Micronésie', aliases: ['Micronesie'] },
  { flag: '🇵🇼', name: 'Palaos' },
  { flag: '🇲🇭', name: 'Îles Marshall', aliases: ['Iles Marshall'] },
  { flag: '🇳🇷', name: 'Nauru' },
  { flag: '🇹🇻', name: 'Tuvalu' },
]

export const ALL_COUNTRIES: Country[] = [...EASY_COUNTRIES, ...HARD_COUNTRIES]
